# Formation sur pandas

In [2]:
import pandas as pd 
df = pd.read_csv('survey_results_public.csv')

#### Pour afficher un certain nombre de ligne

In [14]:
df.head(5)

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,NaN,"Developer, mobile",20 to 99 employees,EUR European Euro,4800.0,Monthly,C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift,Swift,PostgreSQL;SQLite,SQLite,NaN,NaN,Laravel;Symfony,NaN,NaN,NaN,NaN,NaN,PHPStorm;Xcode,Atom;Xcode,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Multiple times per day,Yes,A few times per month or weekly,"Yes, definitely",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
1,2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,NaN,NaN,NaN,NaN,NaN,NaN,JavaScript;Python,NaN,PostgreSQL,NaN,NaN,NaN,Angular;Flask;Vue.js,NaN,Cordova,NaN,Docker;Git;Yarn,Git,Android Studio;IntelliJ;Notepad++;PyCharm,NaN,Windows,Visit Stack Overflow;Google it,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,"Yes, definitely",No,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
2,3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;C;Python;R;Rust,Julia;Python;Rust,SQLite,SQLite,Heroku,NaN,Flask,Flask,NumPy;Pandas;TensorFlow;Torch/PyTorch,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,NaN,NaN,IPython/Jupyter;PyCharm;RStudio;Sublime Text;V...,IPython/Jupyter;RStudio;Sublime Text;Visual St...,MacOS,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,"Yes, definitely",Yes,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
3,4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,NaN,"Developer, front-end",100 to 499 employees,EUR European Euro,NaN,Monthly,JavaScript;TypeScript,JavaScript;TypeScript,NaN,NaN,NaN,NaN,Angular;jQuery,Angular;jQuery,NaN,NaN,NaN,NaN,NaN,NaN,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,Neutral,No,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
4,5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,10,"Developer, desktop or enterprise applications;...","Just me - I am a freelancer, sole proprietor, ...",GBP\tPound sterling,NaN,NaN,Bash/Shell;HTML/CSS;Python;SQL,Bash/Shell;HTML/CSS;Python;SQL,Elasticsearch;PostgreSQL;Redis,Cassandra;Elasticsearch;PostgreSQL;Redis,NaN,NaN,Flask,Flask,Apache Spark;Hadoop;NumPy;Pandas,Hadoop;NumPy;Pandas,Docker;Git;Kubernetes;Yarn,Docker;Git;Kubernetes;Yarn,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim;Vis...,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per week,"Yes, somewhat",No,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN

#### Pour afficher les dernières lignes

In [15]:
df.tail(10)

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
83429,83430,I code primarily as a hobby,"Not employed, but looking for work",United States of America,Washington,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,"Other online resources (ex: videos, blogs, etc)",6,NaN,Other (please specify):;Student,NaN,NaN,NaN,NaN,HTML/CSS;PHP;PowerShell;Python;SQL;VBA,C#;Go;HTML/CSS;Java;JavaScript;PHP;Python;SQL;VBA,MongoDB;MySQL;PostgreSQL,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,Heroku,AWS;Heroku;IBM Cloud or Watson;Microsoft Azure...,Django;Flask;jQuery,Angular.js;ASP.NET;ASP.NET Core ;Django;FastAP...,NumPy;Pandas,.NET Framework;.NET Core / .NET 5;NumPy;Pandas,Git,Docker;Git;Xamarin,Atom;Notepad++;Sublime Text;Visual Studio Code,Atom;Notepad++;Sublime Text;Visual Studio Code,Windows,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange,A few times per month or weekly,Not sure/can't remember,NaN,"Yes, somewhat",No,25-34 years old,"Man;Or, in your own words:",Yes,Queer,White or of European descent,I am unable to / find it difficult to walk or ...,I have an anxiety disorder,Appropriate in length,Neither easy nor difficult,NaN
83430,83431,I am a developer by profession,Employed full-time,United States of America,Illinois,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",23,21,"Developer, front-end;Developer, full-stack;Dev...",10 to 19 employees,USD\tUnited States dollar,125000.0,Yearly,APL;Clojure;LISP;Python;Ruby;SQL;TypeScript,APL;Clojure;Haskell;LISP;R,MongoDB;MySQL;PostgreSQL;Redis,PostgreSQL,AWS;DigitalOcean;Google Cloud Platform;Heroku,AWS;DigitalOcean;Google Cloud Platform,Django;React.js;Ruby on Rails,NaN,NaN,NaN,Docker;Git,Docker;Git;Kubernetes;Unity 3D,Emacs;Vim,Emacs,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,A few times per week,No,NaN,"No, not really",No,45-54 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,125000.0
83431,83432,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Pakistan,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",9,4,"Developer, mobile;Developer, desktop or enterp...",2 to 9 employees,PKR\tPakistani rupee,150000.0,Monthly,C#;Dart;HTML/CSS;Java;JavaScript;Kotlin;Node.j...,C#;Dart;HTML/CSS;JavaScript;Kotlin;Node.js;Pyt...,Firebase;MySQL;SQLite,DynamoDB;Firebase;MongoDB;MySQL;SQLite,Google Cloud Platform,AWS;Google Cloud Platform,Flask;jQuery,Angular;Django;Flask;jQuery;Laravel,Flutter,Flutter;Hadoop;NumPy;TensorFlow;Torch/PyTorch,Git,Docker;Git,Android Studio;IntelliJ;IPython/Jupyter;Notepa...,Android Studio;IntelliJ;IPython/Jupyter;PyChar...,Windows,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,A few times per month or weekly,"Yes, definitely",No,18-24 years old,Man,No,Straight / Heterosexual,Southeast Asian,None of the above,None of the above,Appropriate in length,Easy,11676.0
83432,83433,I am a developer by profession,Employed full-time,Canada,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,School,5,Less than 1 year,"Developer, back-end","10,000 or more employees",CAD\tCanadian dollar,106000.0,Yearly,Ruby,Java;Ruby;TypeScript,MySQL;PostgreSQL,NaN,Google Cloud Platform;Heroku,NaN,Flask;React.js;Ruby on Rails;Vue.js,NaN,NumPy;Pandas;TensorFlow;Torch/PyTorch,NaN,Docker;Git;Kubernetes;Yarn,NaN,Atom;IPython/Jupyter;Vim;Visual Studio Code,NaN,MacOS,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,Daily or almost daily,No,NaN,"No, not really",No,18-24 years old,Woman,No,Straight / Heterosexual,East Asian,None of the above,None of the above,Appropriate in length,Easy,80169.0
83433,83434,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Brazil,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,Online Forum;Online Courses or Certification;O...,15,11,"Developer, mobile;Developer, front-end;Develop...","1,000 to 4,999 employees",BRL\tBrazilian real,80000.0,Yearly,Java;JavaScript;Kotlin;Objective-C;TypeScript,Kotlin,Firebase;MongoDB;MySQL;SQLite,NaN,NaN,NaN,React.js,NaN,React Native,Flutter,Docker;Git;Yarn,Docker;Git,Android Studio;Visual Studio Code;Xcode,Android Studio;Xcode,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Daily or almost daily,Yes,A few times per month or weekly,"Yes, somewhat",No,25-34 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,I have an anxiety disorder,Appropriate in length,Easy,18326.0
83434,83435,I am a developer by profession,Employed full-time,United States of America,Texas,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",6,5,"Developer, back-end",20 to 99 employees,USD\tUnited States dollar,160500.0,Yearly,Clojure;Kotlin;SQL,Clojure,Oracle;SQLite,SQLite,AWS,AWS,NaN,NaN,NaN,NaN,Docker;Git,Git;Kubernetes,IntelliJ;Sublime Text;Vim;Visual Studio Code,Sublime Text;Vim,MacOS,Call a coworker or friend;Google it,Stack Overflow;Stack Exchange,A few times per week,No,NaN,"No, not at all",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,160500.0
83435,83436,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Benin,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",4,2,"Developer, full-stack","Just me - I am a freelancer, sole proprietor, ...",XOF\tWest African CFA franc,200000.0,Monthly,NaN,NaN,Firebase;MariaDB;MySQL;PostgreSQL;Redis;SQLite,Firebase;MariaDB;MongoDB;MySQL;PostgreSQL;Redi...,NaN,NaN,Django;jQuery;Laravel;React.js;Ruby on Rails,Django;Express;jQuery;Laravel;React.js;Ruby on...,Flutter;Qt,NaN,Git;Unity 3D;Unreal Engine,Docker;Git;Kubernetes,Android Studio;Eclipse;Emacs;IntelliJ;NetBeans...,Emacs;IntelliJ;PHPStorm;PyCharm;RStudio;Sublim...,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,I have never participated in Q&A on Stack Over...,"Yes, somewhat",No,18-24 years old,Man,No,Straight / Heterosexual,Black or of African descent,None of the above,None of the above,Appropriate in length,Easy,3960.0
83436,83437,I am a developer by profession,Employed full-time,United States of America,New Jersey,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,School,10,4,Data scientist or machine learning specialist;...,"10,000 or more employees",USD\tUnited States dollar,1800.0,Weekly,Groovy;Java;Python,Java;Python,DynamoDB;Elasticsearch;MongoDB;PostgreSQL;Redis,DynamoDB;Redis,AWS;Google Cloud Platform,AWS,FastAPI;Flask,FastAPI;Flask,Hadoop;Keras;NumPy;Pandas,Apache Spark;Hadoop;Keras;NumPy;Pandas;TensorFlow,Ansible;Docker;Git;Terraform,Docker;Git;Kubernetes;Terraform,Android Studio;Eclipse;IntelliJ;IPython/Jupyte...,IntelliJ;IPython/Jupyter;Notepad++;Vim,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,A few times per week,Yes,I have never participated in Q&A on Stack Over...,"No, not really",No,25-34 years old,Man,No,NaN,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,90000.0
83437,83438,I am a developer by profession,Employed full-time,Canada,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Online Courses or Certification;Books / Physic...,5,3,"Developer, back-end",20 to 99 employees,CAD\tCanadian dollar,90000.0,Monthly,Bash/Shell;JavaScript;Node.js;Python,Go;Rust,Cassandra;Elasticsearch;MongoDB;PostgreSQL;Redis,NaN,Heroku,AWS;DigitalOcean,Django;Express;Flask;React.js,NaN,NumPy;Pandas;TensorFlow;Torch/PyTorch,NumPy;Pandas;TensorFlow;Torch/PyTorch,Ansible;Docker;Git;Terraform,Kubernetes;Terraform,PyCharm;Sublime Text,NaN,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,A few times per month or weekly,Yes,Less than once per month or monthly,"No, not really",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a mood or emotional disorder (e.g. depr...,Appropriate in length,Neither easy nor difficult,816816.0
83438,83439,I am a developer by profession,Employed full-time,Brazil,NaN,NaN,"Professional degree (JD, MD, etc.)",11 - 17 years,School,14,4,"Developer, front-end;Developer, full-stack;Dev...",I don’t know,BRL\tBrazilian real,7700.0,Monthly,Delphi;Elixir;HTML/CSS;Java;JavaScript,Elixir;HTML/CSS;Java;JavaScript;Node.js;PHP;SQ...,Oracle;PostgreSQL,Elasticsearch;MongoDB;MySQL;Oracle;PostgreSQL;...,Microsoft Azure,AWS,Angular;Spring,Express;Laravel;Spring;Symfony,NaN,NaN,Docker;Git,Docker;Git;Kubernetes,IntelliJ;Visual Studio Code,IntelliJ;PHPStorm;Visual Studio Code,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange;Stack Overflow f...,A few times per week,Yes,A few times per week,"Yes, somewhat",No,18-24 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Easy,21168.0

#### La fonction ci-dessous est connaitre le nombre de colonnes et de lignes

In [4]:
df.shape

(83439, 48)

### df.info() est une méthode pour connaitre le type de chaque colonne (Entier / Objet / String / etc ...) et connaitre le nombre de ligne non null dans chaque colonne

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83439 entries, 0 to 83438
Data columns (total 48 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ResponseId                    83439 non-null  int64
 1   MainBranch                    83439 non-null  object
 2   Employment                    83323 non-null  object
 3   Country                       83439 non-null  object
 4   US_State                      14920 non-null  object
 5   UK_Country                    4418 non-null   object
 6   EdLevel                       83126 non-null  object
 7   Age1stCode                    83243 non-null  object
 8   LearnCode                     82963 non-null  object
 9   YearsCode                     81641 non-null  object
 10  YearsCodePro                  61216 non-null  object
 11  DevType                       66484 non-null  object
 12  OrgSize                       60726 non-null  object
 13  Currency                      61080 non-null  object
 14  CompTotal                     47183 non-null  float64
 15  CompFreq                      52150 non-null  object
 16  LanguageHaveWorkedWith        82357 non-null  object
 17  LanguageWantToWorkWith        76821 non-null  object
 18  DatabaseHaveWorkedWith        69546 non-null  object
 19  DatabaseWantToWorkWith        58299 non-null  object
 20  PlatformHaveWorkedWith        52135 non-null  object
 21  PlatformWantToWorkWith        41619 non-null  object
 22  WebframeHaveWorkedWith        61707 non-null  object
 23  WebframeWantToWorkWith        52095 non-null  object
 24  MiscTechHaveWorkedWith        47055 non-null  object
 25  MiscTechWantToWorkWith        38021 non-null  object
 26  ToolsTechHaveWorkedWith       72537 non-null  object
 27  ToolsTechWantToWorkWith       65480 non-null  object
 28  NEWCollabToolsHaveWorkedWith  81234 non-null  object
 29  NEWCollabToolsWantToWorkWith  73022 non-null  object
 30  OpSys                         83294 non-null  object
 31  NEWStuck                      83052 non-null  object
 32  NEWSOSites                    83171 non-null  object
 33  SOVisitFreq                   82413 non-null  object
 34  SOAccount                     82525 non-null  object
 35  SOPartFreq                    67553 non-null  object
 36  SOComm                        82319 non-null  object
 37  NEWOtherComms                 82828 non-null  object
 38  Age                           82407 non-null  object
 39  Gender                        82286 non-null  object
 40  Trans                         80678 non-null  object
 41  Sexuality                     73366 non-null  object
 42  Ethnicity                     79464 non-null  object
 43  Accessibility                 77603 non-null  object
 44  MentalHealth                  76920 non-null  object
 45  SurveyLength                  81711 non-null  object
 46  SurveyEase                    81948 non-null  object
 47  ConvertedCompYearly           46844 non-null  float64
dtypes: float64(2), int64(1), object(45)
memory usage: 30.6+ MB

#### Pour afficher toutes les colonnes

In [6]:
pd.set_option('display.max_columns', 85)

#### Pour afficher toutes les lignes

In [28]:
pd.set_option('display.max_rows', 20)

In [20]:
schema_df = pd.read_csv('./survey_results_schema.csv')
schema_df

,qid,qname,question,force_resp,type,selector
0,QID16,S0,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
1,QID12,MetaInfo,Browser Meta Info,False,Meta,Browser
...,...,...,...,...,...,...
46,QID132,SurveyLength,How do you feel about the length of the survey...,False,MC,MAVR
47,QID133,SurveyEase,How easy or difficult was this survey to compl...,False,MC,MAVR

df.Country

In [29]:
df.groupby('Age1stCode').count()

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
Age1stCode,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
11 - 17 years,44170,44170,44119,44170,7834,2244,44086,44028,43419,32308,34722,32039,32174,25774,27792,43813,41291,36968,31119,27728,22226,32784,27806,25094,20349,39272,35805,43400,39486,44139,44047,44094,43873,43917,36001,43817,43905,43783,43685,43005,39567,42450,41435,41091,43428,43613,25638
18 - 24 years,20065,20065,20054,20065,2730,690,20044,19977,19594,15431,16999,15413,15504,11434,13132,19739,18188,17115,14397,12615,10217,15195,12981,11175,9108,16902,15080,19434,17151,20032,19987,19996,19752,19791,16252,19736,19923,19818,19804,19288,17288,18900,18510,18253,19630,19655,11331
25 - 34 years,4199,4199,4197,4199,728,199,4194,4172,4082,3403,3858,3420,3434,2470,2931,4086,3702,3538,2903,2660,2092,3133,2620,2206,1740,3432,2991,4009,3462,4187,4168,4176,4098,4104,3353,4080,4162,4149,4146,4039,3654,3969,3862,3833,4080,4088,2443
35 - 44 years,1312,1312,1312,1312,221,77,1306,1303,1275,1074,1213,1052,1060,742,879,1269,1121,1112,907,848,658,947,789,704,541,1053,901,1239,1064,1308,1299,1306,1268,1269,1037,1268,1302,1298,1295,1246,1119,1236,1197,1188,1271,1256,736
45 - 54 years,544,544,543,544,103,38,539,540,523,469,516,445,446,296,341,526,456,464,370,307,229,354,273,278,201,410,340,505,417,542,539,542,520,521,398,519,540,536,534,515,460,511,489,486,519,519,291
5 - 10 years,11720,11720,11691,11720,3038,1109,11633,11651,11518,7728,8273,7590,7623,6001,6437,11633,10955,9312,7786,7241,5664,8426,6961,6881,5537,10489,9546,11459,10466,11709,11671,11698,11644,11657,9564,11641,11653,11520,11519,11350,10217,11177,10926,10886,11498,11546,5951
55 - 64 years,245,245,244,245,66,13,245,241,231,197,202,185,187,110,128,228,186,196,154,115,83,123,88,129,97,151,123,210,167,242,242,243,229,228,167,230,241,240,240,229,198,230,227,228,232,237,107
Older than 64 years,83,83,82,83,18,4,82,81,73,56,41,36,36,15,23,68,52,41,31,26,16,28,17,29,22,34,25,53,39,79,78,81,60,60,37,60,80,81,80,76,69,78,77,77,76,77,14
Younger than 5 years,905,905,900,905,153,40,897,894,858,516,604,515,522,330,456,851,755,698,560,519,386,635,500,495,380,704,600,810,686,897,886,890,838,839,656,837,889,886,884,850,733,839,812,808,867,848,322